Repository OCA/account-closing, pull requests merged in 2019-04, with the labels that each got.

#101 [11.0] account_multicurrency_revaluation: Fixes and improvements
  account_multicurrency_revaluation/model/__init__.py
  account_multicurrency_revaluation/model/res_currency.py
  account_multicurrency_revaluation/tests/test_currency_revaluation.py
  account_multicurrency_revaluation/wizard/wizard_currency_revaluation.py
Labels: approved

#102 [10.0] account_multicurrency_revaluation: Fixes and improvements
  account_multicurrency_revaluation/model/__init__.py
  account_multicurrency_revaluation/model/res_currency.py
  account_multicurrency_revaluation/tests/test_currency_revaluation.py
  account_multicurrency_revaluation/wizard/wizard_currency_revaluation.py
Labels: approved

#103 [12.0] account_multicurrency_revaluation: Fixes and improvements
  account_multicurrency_revaluation/model/__init__.py
  account_multicurrency_revaluation/model/res_currency.py
  account_multicurrency_revaluation/tests/test_currency_revaluation.py
  account_multicurrency_revaluation/wizard/wizard_currency_revaluation.py
Labels: approved

#89 [12.0] [mig] account invoice start end dates
  account_invoice_start_end_dates/README.rst
  account_invoice_start_end_dates/__init__.py
  account_invoice_start_end_dates/__manifest__.py
  account_invoice_start_end_dates/demo/product_demo.xml
  account_invoice_start_end_dates/i18n/account_invoice_start_end_dates.pot
  account_invoice_start_end_dates/i18n/fr.po
  account_invoice_start_end_dates/i18n/hr.po
  account_invoice_start_end_dates/i18n/hr_HR.po
  account_invoice_start_end_dates/i18n/it.po
  account_invoice_start_end_dates/i18n/nl_NL.po
  account_invoice_start_end_dates/i18n/pt.po
  account_invoice_start_end_dates/models/__init__.py
  account_invoice_start_end_dates/models/account_invoice.py
  account_invoice_start_end_dates/models/account_move_line.py
  account_invoice_start_end_dates/models/product.py
  account_invoice_start_end_dates/readme/CONTRIBUTORS.rst
  account_invoice_start_end_dates/readme/DESCRIPTION.rst
  account_invoice_start_end_dates/static/description/index.html
  account_invoice_start_end_dates/tests/__init__.py
  account_invoice_start_end_dates/tests/test_invoice_start_end_dates.py
  account_invoice_start_end_dates/views/account_invoice.xml
  account_invoice_start_end_dates/views/account_move.xml
  account_invoice_start_end_dates/views/product.xml
Labels: approved, needs review, ready to merge

#109 [10.0] FIX bug rounding debit/credit
  account_cutoff_accrual_dates/models/account_cutoff.py
  account_cutoff_base/models/account_cutoff.py
  account_cutoff_prepaid/models/account_cutoff.py
Labels: needs review
