Repository OCA/account-closing, pull requests merged in 2022-08, with the labels that each got.

#193 [15.0][MIG] account_cutoff_accrual_subscription
  account_cutoff_accrual_subscription/README.rst
  account_cutoff_accrual_subscription/__init__.py
  account_cutoff_accrual_subscription/__manifest__.py
  account_cutoff_accrual_subscription/i18n/account_cutoff_accrual_subscription.pot
  account_cutoff_accrual_subscription/models/__init__.py
  account_cutoff_accrual_subscription/models/account_cutoff.py
  account_cutoff_accrual_subscription/models/account_cutoff_accrual_subscription.py
  account_cutoff_accrual_subscription/readme/CONFIGURE.rst
  account_cutoff_accrual_subscription/readme/CONTRIBUTORS.rst
  account_cutoff_accrual_subscription/readme/DESCRIPTION.rst
  account_cutoff_accrual_subscription/security/ir.model.access.csv
  account_cutoff_accrual_subscription/security/ir_rule.xml
  account_cutoff_accrual_subscription/static/description/icon.png
  account_cutoff_accrual_subscription/static/description/index.html
  account_cutoff_accrual_subscription/views/account_cutoff_accrual_subscription.xml
  setup/account_cutoff_accrual_subscription/odoo/addons/account_cutoff_accrual_subscription
  setup/account_cutoff_accrual_subscription/setup.py
Labels: bot is merging ⏳, stale

#169 [14.0][MIG] account_fiscal_year_closing
  account_fiscal_year_closing/README.rst
  account_fiscal_year_closing/__init__.py
  account_fiscal_year_closing/__manifest__.py
  account_fiscal_year_closing/i18n/account_fiscal_year_closing.pot
  account_fiscal_year_closing/i18n/es.po
  account_fiscal_year_closing/i18n/fr.po
  account_fiscal_year_closing/i18n/hr.po
  account_fiscal_year_closing/i18n/it.po
  account_fiscal_year_closing/i18n/nl_NL.po
  account_fiscal_year_closing/i18n/pt.po
  account_fiscal_year_closing/i18n/pt_BR.po
  account_fiscal_year_closing/models/__init__.py
  account_fiscal_year_closing/models/account_fiscalyear_closing.py
  account_fiscal_year_closing/models/account_fiscalyear_closing_abstract.py
  account_fiscal_year_closing/models/account_fiscalyear_closing_template.py
  account_fiscal_year_closing/models/account_move.py
  account_fiscal_year_closing/readme/CONFIGURE.rst
  account_fiscal_year_closing/readme/CONTRIBUTORS.rst
  account_fiscal_year_closing/readme/DESCRIPTION.rst
  account_fiscal_year_closing/readme/USAGE.rst
  account_fiscal_year_closing/security/account_fiscalyear_closing_security.xml
  account_fiscal_year_closing/security/ir.model.access.csv
  account_fiscal_year_closing/static/description/icon.png
  account_fiscal_year_closing/static/description/icon.svg
  account_fiscal_year_closing/static/description/index.html
  account_fiscal_year_closing/tests/__init__.py
  account_fiscal_year_closing/tests/test_account_fiscal_year_closing.py
  account_fiscal_year_closing/views/account_fiscalyear_closing_template_views.xml
  account_fiscal_year_closing/views/account_fiscalyear_closing_views.xml
  account_fiscal_year_closing/views/account_move_views.xml
  account_fiscal_year_closing/wizards/__init__.py
  account_fiscal_year_closing/wizards/account_fiscal_year_closing_unbalanced_move.py
  account_fiscal_year_closing/wizards/account_fiscal_year_closing_unbalanced_move_views.xml
  setup/account_fiscal_year_closing/odoo/addons/account_fiscal_year_closing
  setup/account_fiscal_year_closing/setup.py
Labels: approved, ready to merge

#199 14.0 mig account fiscal year closing
  account_fiscal_year_closing/README.rst
  account_fiscal_year_closing/__init__.py
  account_fiscal_year_closing/__manifest__.py
  account_fiscal_year_closing/i18n/account_fiscal_year_closing.pot
  account_fiscal_year_closing/i18n/es.po
  account_fiscal_year_closing/i18n/fr.po
  account_fiscal_year_closing/i18n/hr.po
  account_fiscal_year_closing/i18n/it.po
  account_fiscal_year_closing/i18n/nl_NL.po
  account_fiscal_year_closing/i18n/pt.po
  account_fiscal_year_closing/i18n/pt_BR.po
  account_fiscal_year_closing/models/__init__.py
  account_fiscal_year_closing/models/account_fiscalyear_closing.py
  account_fiscal_year_closing/models/account_fiscalyear_closing_abstract.py
  account_fiscal_year_closing/models/account_fiscalyear_closing_template.py
  account_fiscal_year_closing/models/account_move.py
  account_fiscal_year_closing/readme/CONFIGURE.rst
  account_fiscal_year_closing/readme/CONTRIBUTORS.rst
  account_fiscal_year_closing/readme/DESCRIPTION.rst
  account_fiscal_year_closing/readme/USAGE.rst
  account_fiscal_year_closing/security/account_fiscalyear_closing_security.xml
  account_fiscal_year_closing/security/ir.model.access.csv
  account_fiscal_year_closing/static/description/icon.png
  account_fiscal_year_closing/static/description/icon.svg
  account_fiscal_year_closing/static/description/index.html
  account_fiscal_year_closing/tests/__init__.py
  account_fiscal_year_closing/tests/test_account_fiscal_year_closing.py
  account_fiscal_year_closing/views/account_fiscalyear_closing_template_views.xml
  account_fiscal_year_closing/views/account_fiscalyear_closing_views.xml
  account_fiscal_year_closing/views/account_move_views.xml
  account_fiscal_year_closing/wizards/__init__.py
  account_fiscal_year_closing/wizards/account_fiscal_year_closing_unbalanced_move.py
  account_fiscal_year_closing/wizards/account_fiscal_year_closing_unbalanced_move_views.xml
  setup/account_fiscal_year_closing/odoo/addons/account_fiscal_year_closing
  setup/account_fiscal_year_closing/setup.py
Labels: approved, ready to merge, bot is merging ⏳
