Repository OCA/account-closing, pull requests merged in 2022-10, with the labels that each got.

#195 [14.0] account_invoice_start_end_dates: add start/end dates in tree view of move lines
  account_invoice_start_end_dates/__manifest__.py
  account_invoice_start_end_dates/views/account_move.xml
  account_invoice_start_end_dates/views/account_move_line.xml
Labels: approved, ready to merge, bot is merging ⏳

#204 [13.0][IMP]account_multicurrency_revaluation: Auto-Post Entries Setting
  account_multicurrency_revaluation/model/res_company.py
  account_multicurrency_revaluation/model/res_config.py
  account_multicurrency_revaluation/views/res_config_view.xml
  account_multicurrency_revaluation/wizard/wizard_currency_revaluation.py
Labels: approved, ready to merge, bot is merging ⏳

#207 [13.0][UPD] dotfiles
  .copier-answers.yml
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  account_multicurrency_revaluation/__manifest__.py
Labels: bot is merging ⏳

#205 [14.0] cutoff: add option to filter source move on state
  account_cutoff_accrual_subscription/models/account_cutoff.py
  account_cutoff_accrual_subscription/models/account_cutoff_accrual_subscription.py
  account_cutoff_base/models/account_cutoff.py
  account_cutoff_base/models/res_company.py
  account_cutoff_base/views/account_cutoff.xml
  account_cutoff_base/views/res_config_settings.xml
  account_cutoff_base/wizards/res_config_settings.py
  account_cutoff_start_end_dates/models/account_cutoff.py
  account_cutoff_start_end_dates/views/account_cutoff.xml
Labels: needs review, bot is merging ⏳

#206 [16.0][MIG] account_invoice_start_end_dates: Migration to 16.0
  account_invoice_start_end_dates/README.rst
  account_invoice_start_end_dates/__init__.py
  account_invoice_start_end_dates/__manifest__.py
  account_invoice_start_end_dates/demo/product_demo.xml
  account_invoice_start_end_dates/i18n/account_invoice_start_end_dates.pot
  account_invoice_start_end_dates/i18n/fr.po
  account_invoice_start_end_dates/i18n/fr_FR.po
  account_invoice_start_end_dates/i18n/hr.po
  account_invoice_start_end_dates/i18n/hr_HR.po
  account_invoice_start_end_dates/i18n/it.po
  account_invoice_start_end_dates/i18n/nl_NL.po
  account_invoice_start_end_dates/i18n/pt.po
  account_invoice_start_end_dates/models/__init__.py
  account_invoice_start_end_dates/models/account_move.py
  account_invoice_start_end_dates/models/account_move_line.py
  account_invoice_start_end_dates/models/product_template.py
  account_invoice_start_end_dates/readme/CONTRIBUTORS.rst
  account_invoice_start_end_dates/readme/DESCRIPTION.rst
  account_invoice_start_end_dates/static/description/icon.png
  account_invoice_start_end_dates/static/description/index.html
  account_invoice_start_end_dates/tests/__init__.py
  account_invoice_start_end_dates/tests/test_invoice_start_end_dates.py
  account_invoice_start_end_dates/views/account_move.xml
  account_invoice_start_end_dates/views/product_template.xml
  setup/account_invoice_start_end_dates/odoo/addons/account_invoice_start_end_dates
  setup/account_invoice_start_end_dates/setup.py
Labels: approved, ready to merge, bot is merging ⏳
