Repository OCA/account-closing, pull requests merged in 2022-01, with the labels that each got.

#165 [12.0][IMP] closing type not null
  account_fiscal_year_closing/__manifest__.py
  account_fiscal_year_closing/migrations/12.0.1.2.0/pre-migration.py
  account_fiscal_year_closing/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳

#188 [15.0][MIG] account_invoice_start_end_dates
  account_invoice_start_end_dates/README.rst
  account_invoice_start_end_dates/__init__.py
  account_invoice_start_end_dates/__manifest__.py
  account_invoice_start_end_dates/demo/product_demo.xml
  account_invoice_start_end_dates/i18n/account_invoice_start_end_dates.pot
  account_invoice_start_end_dates/i18n/fr.po
  account_invoice_start_end_dates/i18n/fr_FR.po
  account_invoice_start_end_dates/i18n/hr.po
  account_invoice_start_end_dates/i18n/hr_HR.po
  account_invoice_start_end_dates/i18n/it.po
  account_invoice_start_end_dates/i18n/nl_NL.po
  account_invoice_start_end_dates/i18n/pt.po
  account_invoice_start_end_dates/models/__init__.py
  account_invoice_start_end_dates/models/account_move.py
  account_invoice_start_end_dates/models/account_move_line.py
  account_invoice_start_end_dates/models/product_template.py
  account_invoice_start_end_dates/readme/CONTRIBUTORS.rst
  account_invoice_start_end_dates/readme/DESCRIPTION.rst
  account_invoice_start_end_dates/static/description/icon.png
  account_invoice_start_end_dates/static/description/index.html
  account_invoice_start_end_dates/tests/__init__.py
  account_invoice_start_end_dates/tests/test_invoice_start_end_dates.py
  account_invoice_start_end_dates/views/account_move.xml
  account_invoice_start_end_dates/views/product_template.xml
  setup/account_invoice_start_end_dates/odoo/addons/account_invoice_start_end_dates
  setup/account_invoice_start_end_dates/setup.py
Labels: approved, bot is merging ⏳

#191 [15.0][MIG] account_cutoff_accrual_picking
  account_cutoff_accrual_picking/README.rst
  account_cutoff_accrual_picking/__init__.py
  account_cutoff_accrual_picking/__manifest__.py
  account_cutoff_accrual_picking/i18n/account_cutoff_accrual_picking.pot
  account_cutoff_accrual_picking/i18n/de.po
  account_cutoff_accrual_picking/i18n/it.po
  account_cutoff_accrual_picking/images/accrued_expense_done.jpg
  account_cutoff_accrual_picking/images/accrued_expense_draft.jpg
  account_cutoff_accrual_picking/images/accrued_expense_journal_entry.jpg
  account_cutoff_accrual_picking/models/__init__.py
  account_cutoff_accrual_picking/models/account_cutoff.py
  account_cutoff_accrual_picking/models/res_company.py
  account_cutoff_accrual_picking/readme/CONFIGURE.rst
  account_cutoff_accrual_picking/readme/CONTRIBUTORS.rst
  account_cutoff_accrual_picking/readme/DESCRIPTION.rst
  account_cutoff_accrual_picking/static/description/icon.png
  account_cutoff_accrual_picking/static/description/index.html
  account_cutoff_accrual_picking/static/src/img/icon.png
  account_cutoff_accrual_picking/views/account_cutoff.xml
  account_cutoff_accrual_picking/views/res_config_settings.xml
  account_cutoff_accrual_picking/wizards/__init__.py
  account_cutoff_accrual_picking/wizards/res_config_settings.py
  setup/account_cutoff_accrual_picking/odoo/addons/account_cutoff_accrual_picking
  setup/account_cutoff_accrual_picking/setup.py
Labels: bot is merging ⏳
