Repository OCA/account-closing, pull requests merged in 2023-03, with the labels that each got.

#221 [14.0][FW]account_multicurrency_revaluation: Auto-Post Entries Setting
  account_multicurrency_revaluation/model/res_company.py
  account_multicurrency_revaluation/model/res_config.py
  account_multicurrency_revaluation/views/res_config_view.xml
  account_multicurrency_revaluation/wizard/wizard_currency_revaluation.py
Labels: approved, bot is merging ⏳

#222 [15.0][FW]account_multicurrency_revaluation: Auto-Post Entries Setting
  account_multicurrency_revaluation/model/res_company.py
  account_multicurrency_revaluation/model/res_config.py
  account_multicurrency_revaluation/views/res_config_view.xml
  account_multicurrency_revaluation/wizard/wizard_currency_revaluation.py
Labels: approved, bot is merging ⏳

#200 [13.0][FW] account_multicurrency_revaluation: forward port PR#149
  account_multicurrency_revaluation/__manifest__.py
  account_multicurrency_revaluation/model/account.py
  account_multicurrency_revaluation/model/res_company.py
  account_multicurrency_revaluation/model/res_config.py
  account_multicurrency_revaluation/readme/CONTRIBUTORS.rst
  account_multicurrency_revaluation/readme/INSTALL.rst
  account_multicurrency_revaluation/readme/USAGE.rst
  account_multicurrency_revaluation/report/currency_unrealized_report.py
  account_multicurrency_revaluation/report/unrealized_currency_gain_loss.xml
  account_multicurrency_revaluation/tests/__init__.py
  account_multicurrency_revaluation/tests/test_account_account.py
  account_multicurrency_revaluation/tests/test_currency_revaluation.py
  account_multicurrency_revaluation/views/account_move_line_views.xml
  account_multicurrency_revaluation/views/account_move_views.xml
  account_multicurrency_revaluation/views/res_config_view.xml
  account_multicurrency_revaluation/wizard/__init__.py
  account_multicurrency_revaluation/wizard/print_currency_unrealized_report.py
  account_multicurrency_revaluation/wizard/print_currency_unrealized_report_view.xml
  account_multicurrency_revaluation/wizard/wizard_currency_revaluation.py
  account_multicurrency_revaluation/wizard/wizard_currency_revaluation_view.xml
  account_multicurrency_revaluation/wizard/wizard_reverse_currency_revaluation.py
  account_multicurrency_revaluation/wizard/wizard_reverse_currency_revaluation_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#241 Add copier
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  account_cutoff_accrual_base/__manifest__.py
  account_cutoff_accrual_dates/__manifest__.py
  account_cutoff_accrual_dates/i18n/es.po
  account_cutoff_accrual_picking/i18n/de.po
  account_multicurrency_revaluation/__manifest__.py
Labels: bot is merging ⏳

#209 [14.0][FIX] - account_fiscal_year_closing - closing procedure compute…
  account_fiscal_year_closing/models/account_fiscalyear_closing.py
Labels: approved, ready to merge, bot is merging ⏳, stale
