Repository OCA/account-closing, pull requests merged in 2023-02, with the labels that each got.

#232 [16.0] account_cutoff_base: update README
  account_cutoff_base/readme/DESCRIPTION.rst
Labels: bot is merging ⏳

#216 [MIG] account_cutoff_start_end_dates: Migration to 16.0
  account_cutoff_start_end_dates/README.rst
  account_cutoff_start_end_dates/__init__.py
  account_cutoff_start_end_dates/__manifest__.py
  account_cutoff_start_end_dates/i18n/account_cutoff_prepaid.pot
  account_cutoff_start_end_dates/i18n/account_cutoff_start_end_dates.pot
  account_cutoff_start_end_dates/i18n/am.po
  account_cutoff_start_end_dates/i18n/ar.po
  account_cutoff_start_end_dates/i18n/da.po
  account_cutoff_start_end_dates/i18n/de.po
  account_cutoff_start_end_dates/i18n/el_GR.po
  account_cutoff_start_end_dates/i18n/es.po
  account_cutoff_start_end_dates/i18n/es_CO.po
  account_cutoff_start_end_dates/i18n/es_ES.po
  account_cutoff_start_end_dates/i18n/es_MX.po
  account_cutoff_start_end_dates/i18n/fi.po
  account_cutoff_start_end_dates/i18n/fr.po
  account_cutoff_start_end_dates/i18n/fr_FR.po
  account_cutoff_start_end_dates/i18n/hr.po
  account_cutoff_start_end_dates/i18n/hr_HR.po
  account_cutoff_start_end_dates/i18n/it.po
  account_cutoff_start_end_dates/i18n/nb.po
  account_cutoff_start_end_dates/i18n/nb_NO.po
  account_cutoff_start_end_dates/i18n/nl.po
  account_cutoff_start_end_dates/i18n/nl_BE.po
  account_cutoff_start_end_dates/i18n/nl_NL.po
  account_cutoff_start_end_dates/i18n/pt.po
  account_cutoff_start_end_dates/i18n/pt_BR.po
  account_cutoff_start_end_dates/i18n/ro.po
  account_cutoff_start_end_dates/i18n/sk.po
  account_cutoff_start_end_dates/i18n/sl.po
  account_cutoff_start_end_dates/i18n/tr.po
  account_cutoff_start_end_dates/i18n/zh_CN.po
  account_cutoff_start_end_dates/images/prepaid_revenue_done.jpg
  account_cutoff_start_end_dates/images/prepaid_revenue_draft.jpg
  account_cutoff_start_end_dates/images/prepaid_revenue_journal_entry.jpg
  account_cutoff_start_end_dates/migrations/16.0.1.0.0/pre-migration.py
  account_cutoff_start_end_dates/models/__init__.py
  account_cutoff_start_end_dates/models/account_cutoff.py
  account_cutoff_start_end_dates/models/account_cutoff_line.py
  account_cutoff_start_end_dates/readme/CONFIGURE.rst
  account_cutoff_start_end_dates/readme/CONTRIBUTORS.rst
  account_cutoff_start_end_dates/readme/CREDITS.rst
  account_cutoff_start_end_dates/readme/DESCRIPTION.rst
  account_cutoff_start_end_dates/readme/USAGE.rst
  account_cutoff_start_end_dates/static/description/icon.png
  account_cutoff_start_end_dates/static/description/index.html
  account_cutoff_start_end_dates/tests/__init__.py
  account_cutoff_start_end_dates/tests/test_account_cutoff_prepaid.py
  account_cutoff_start_end_dates/views/account_cutoff.xml
  account_cutoff_start_end_dates/views/account_cutoff_line.xml
  setup/account_cutoff_start_end_dates/odoo/addons/account_cutoff_start_end_dates
  setup/account_cutoff_start_end_dates/setup.py
Labels: approved, bot is merging ⏳

#233 [14.0] Update pre-commit conf + GH actions
  .copier-answers.yml
  .github/workflows/test.yml
  .travis.yml
  README.md
Labels: needs review

#235 [16.0][MIG] ```account_cutoff_picking``` (ex ```account_cutoff_accrual_picking```)
  account_cutoff_picking/README.rst
  account_cutoff_picking/__init__.py
  account_cutoff_picking/__manifest__.py
  account_cutoff_picking/i18n/account_cutoff_accrual_picking.pot
  account_cutoff_picking/i18n/account_cutoff_picking.pot
  account_cutoff_picking/i18n/de.po
  account_cutoff_picking/i18n/fr_BE.po
  account_cutoff_picking/i18n/fr_FR.po
  account_cutoff_picking/i18n/it.po
  account_cutoff_picking/images/accrued_expense_done.jpg
  account_cutoff_picking/images/accrued_expense_draft.jpg
  account_cutoff_picking/images/accrued_expense_journal_entry.jpg
  account_cutoff_picking/migrations/16.0.1.0.0/pre-migration.py
  account_cutoff_picking/models/__init__.py
  account_cutoff_picking/models/account_cutoff.py
  account_cutoff_picking/models/res_company.py
  account_cutoff_picking/readme/CONFIGURE.rst
  account_cutoff_picking/readme/CONTRIBUTORS.rst
  account_cutoff_picking/readme/DESCRIPTION.rst
  account_cutoff_picking/static/description/icon.png
  account_cutoff_picking/static/description/index.html
  account_cutoff_picking/static/src/img/icon.png
  account_cutoff_picking/views/account_cutoff.xml
  account_cutoff_picking/views/res_config_settings.xml
  account_cutoff_picking/wizards/__init__.py
  account_cutoff_picking/wizards/res_config_settings.py
  setup/account_cutoff_picking/odoo/addons/account_cutoff_picking
  setup/account_cutoff_picking/setup.py
Labels: bot is merging ⏳
