Repository OCA/account-closing, pull requests merged in 2023-08, with the labels that each got.

#255 [14.0][ADD] new module account_invoice_start_end_dates_move
  account_invoice_start_end_dates_move/README.rst
  account_invoice_start_end_dates_move/__init__.py
  account_invoice_start_end_dates_move/__manifest__.py
  account_invoice_start_end_dates_move/i18n/it.po
  account_invoice_start_end_dates_move/models/__init__.py
  account_invoice_start_end_dates_move/models/account_move.py
  account_invoice_start_end_dates_move/models/res_company.py
  account_invoice_start_end_dates_move/models/res_config_settings.py
  account_invoice_start_end_dates_move/readme/CONFIGURE.rst
  account_invoice_start_end_dates_move/readme/CONTRIBUTORS.rst
  account_invoice_start_end_dates_move/readme/DESCRIPTION.rst
  account_invoice_start_end_dates_move/readme/USAGE.rst
  account_invoice_start_end_dates_move/static/description/icon.png
  account_invoice_start_end_dates_move/static/description/index.html
  account_invoice_start_end_dates_move/tests/__init__.py
  account_invoice_start_end_dates_move/tests/test_account_invoice_start_end_dates_move.py
  account_invoice_start_end_dates_move/views/account_move.xml
  account_invoice_start_end_dates_move/views/res_config_settings.xml
  setup/account_invoice_start_end_dates_move/odoo/addons/account_invoice_start_end_dates_move
  setup/account_invoice_start_end_dates_move/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#242 [14.0][FWP] account_multicurrency_revaluation
  account_multicurrency_revaluation/__manifest__.py
  account_multicurrency_revaluation/model/account.py
  account_multicurrency_revaluation/model/res_company.py
  account_multicurrency_revaluation/model/res_config.py
  account_multicurrency_revaluation/readme/CONTRIBUTORS.rst
  account_multicurrency_revaluation/report/currency_unrealized_report.py
  account_multicurrency_revaluation/report/unrealized_currency_gain_loss.xml
  account_multicurrency_revaluation/tests/test_account_account.py
  account_multicurrency_revaluation/tests/test_currency_revaluation.py
  account_multicurrency_revaluation/views/account_move_line_views.xml
  account_multicurrency_revaluation/views/account_move_views.xml
  account_multicurrency_revaluation/views/res_config_view.xml
  account_multicurrency_revaluation/wizard/__init__.py
  account_multicurrency_revaluation/wizard/print_currency_unrealized_report.py
  account_multicurrency_revaluation/wizard/print_currency_unrealized_report_view.xml
  account_multicurrency_revaluation/wizard/wizard_currency_revaluation.py
  account_multicurrency_revaluation/wizard/wizard_currency_revaluation_view.xml
  account_multicurrency_revaluation/wizard/wizard_reverse_currency_revaluation.py
  account_multicurrency_revaluation/wizard/wizard_reverse_currency_revaluation_view.xml
Labels: approved, bot is merging ⏳

#258 [14.0][FIX] account_multicurrency_revaluation: pump version number
  account_multicurrency_revaluation/__manifest__.py
Labels: bot is merging ⏳

#260 [15.0][FIX] account_cutoff_accrual_subscription (bad translation) [greenifying repo]
  account_cutoff_accrual_subscription/i18n/account_cutoff_accrual_subscription.pot
  account_cutoff_accrual_subscription/i18n/es.po
  account_cutoff_accrual_subscription/models/account_cutoff.py
Labels: bot is merging ⏳
