Repository OCA/account-closing, pull requests merged in 2024-02, with the labels that each got.

#266 [16][ account_cutoff_picking] Avoid creating null cut-off line
  account_cutoff_picking/models/account_cutoff.py
Labels: bot is merging ⏳, stale

#291 [17.0] cutoff modules migration fixes
  account_cutoff_base/README.rst
  account_cutoff_base/__manifest__.py
  account_cutoff_base/static/description/index.html
  account_cutoff_base/views/account_cutoff.xml
  account_cutoff_base/views/res_config_settings.xml
  account_cutoff_picking/README.rst
  account_cutoff_picking/__manifest__.py
  account_cutoff_picking/static/description/index.html
  account_cutoff_picking/views/res_config_settings.xml
  account_cutoff_start_end_dates/views/account_cutoff.xml
  account_invoice_start_end_dates/views/account_move.xml
Labels: bot is merging ⏳

#290 [17.0][MIG] account_cutoff_accrual_subscription
  account_cutoff_accrual_subscription/README.rst
  account_cutoff_accrual_subscription/__init__.py
  account_cutoff_accrual_subscription/__manifest__.py
  account_cutoff_accrual_subscription/i18n/account_cutoff_accrual_subscription.pot
  account_cutoff_accrual_subscription/i18n/es.po
  account_cutoff_accrual_subscription/i18n/fr.po
  account_cutoff_accrual_subscription/models/__init__.py
  account_cutoff_accrual_subscription/models/account_cutoff.py
  account_cutoff_accrual_subscription/models/account_cutoff_accrual_subscription.py
  account_cutoff_accrual_subscription/models/account_cutoff_line.py
  account_cutoff_accrual_subscription/pyproject.toml
  account_cutoff_accrual_subscription/readme/CONFIGURE.md
  account_cutoff_accrual_subscription/readme/CONTRIBUTORS.md
  account_cutoff_accrual_subscription/readme/DESCRIPTION.md
  account_cutoff_accrual_subscription/security/ir.model.access.csv
  account_cutoff_accrual_subscription/security/ir_rule.xml
  account_cutoff_accrual_subscription/static/description/icon.png
  account_cutoff_accrual_subscription/static/description/index.html
  account_cutoff_accrual_subscription/views/account_cutoff_accrual_subscription.xml
  account_cutoff_accrual_subscription/views/account_cutoff_line.xml
Labels: bot is merging ⏳

#292 [16.0][MIG] ``account_invoice_start_end_dates_move``
  account_invoice_start_end_dates_move/README.rst
  account_invoice_start_end_dates_move/__init__.py
  account_invoice_start_end_dates_move/__manifest__.py
  account_invoice_start_end_dates_move/i18n/account_invoice_start_end_dates_move.pot
  account_invoice_start_end_dates_move/i18n/es.po
  account_invoice_start_end_dates_move/i18n/it.po
  account_invoice_start_end_dates_move/models/__init__.py
  account_invoice_start_end_dates_move/models/account_move.py
  account_invoice_start_end_dates_move/models/res_company.py
  account_invoice_start_end_dates_move/models/res_config_settings.py
  account_invoice_start_end_dates_move/readme/CONFIGURE.rst
  account_invoice_start_end_dates_move/readme/CONTRIBUTORS.rst
  account_invoice_start_end_dates_move/readme/DESCRIPTION.rst
  account_invoice_start_end_dates_move/readme/USAGE.rst
  account_invoice_start_end_dates_move/static/description/icon.png
  account_invoice_start_end_dates_move/static/description/index.html
  account_invoice_start_end_dates_move/tests/__init__.py
  account_invoice_start_end_dates_move/tests/test_account_invoice_start_end_dates_move.py
  account_invoice_start_end_dates_move/views/account_move.xml
  account_invoice_start_end_dates_move/views/res_config_settings.xml
  setup/account_invoice_start_end_dates_move/odoo/addons/account_invoice_start_end_dates_move
  setup/account_invoice_start_end_dates_move/setup.py
Labels: approved, ready to merge, bot is merging ⏳
