Repository OCA/account-closing, pull requests merged in 2024-10, with the labels that each got.

#305 [14.0] account_move_cutoff: forward product info + settings improvements
  account_move_cutoff/models/account_move_line.py
  account_move_cutoff/models/res_config_settings.py
  account_move_cutoff/tests/test_account_invoice_cutoff.py
  account_move_cutoff/tests/test_account_supplier_refund_cutoff.py
  account_move_cutoff/views/account_move.xml
  account_move_cutoff/views/account_move_line.xml
  account_move_cutoff/views/res_config_settings.xml
Labels: approved, ready to merge, bot is merging ⏳

#270 [16.0][IMP] account_cutoff_base: auto reverse
  account_cutoff_base/__manifest__.py
  account_cutoff_base/i18n/fr.po
  account_cutoff_base/models/account_cutoff.py
  account_cutoff_base/readme/CONTRIBUTORS.rst
  account_cutoff_base/tests/test_account_cutoff.py
  account_cutoff_base/views/account_cutoff.xml
Labels: bot is merging ⏳, no stale

#283 [16.0][MIG] account_cutoff_base: Allow to configure different account for refunds (credit notes)
  account_cutoff_base/i18n/fr.po
  account_cutoff_base/models/res_company.py
  account_cutoff_base/views/res_config_settings.xml
  account_cutoff_base/wizards/res_config_settings.py
Labels: needs review, bot is merging ⏳, no stale
